# Environment variables required in CircleCI:
#
#         $NPM_TOKEN -- NPM publishing auth token.
# $GITHUB_REPO_TOKEN -- GitHub repo-scoped auth token (for use with GREN).

version: 2.1

aliases:
  - &workspace-root
    /home/circleci/project

  - &attach-workspace
    attach_workspace:
      at: *workspace-root

  - &dependency-cache-key
    v1-dependency-cache-{{ checksum "yarn.lock" }}

  - &dependency-paths
    paths:
      - node_modules

  - &dist-paths
    paths:
      - dist

  - &semver-regex
    /^v\d+\.\d+\.\d+$/

  - &filter-tagged
    filters:
      tags:
        only: *semver-regex
      branches:
        ignore: /.*/

  - &filter-untagged
    filters:
      tags:
        ignore: /.*/
      branches:
        only: /.*/

executors:
  default:
    docker:
      - image: circleci/node:10-browsers
  github:
    docker:
      - image: cibuilds/github:0.10

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - restore_cache:
          key: *dependency-cache-key
      - run:
          name: Install App Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          <<: *dependency-paths
          key: *dependency-cache-key
      - persist_to_workspace:
          <<: *dependency-paths
          root: *workspace-root

  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint TypeScripts
          command: yarn lint

  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Build modules
          command: yarn build
      - persist_to_workspace:
          <<: *dist-paths
          root: *workspace-root

  test:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run tests
          command: yarn test

  release:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish packages to NPM
          command: npm publish

  publish-release-to-github:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Install github-release-notes package
          command: yarn add github-release-notes
      - run:
          name: Create a release and publish to GitHub
          command: gren --override --token $GITHUB_REPO_TOKEN

workflows:
  version: 2.1

  pull-request:
    jobs:
      - install-dependencies: *filter-untagged

      - lint:
          requires:
            - install-dependencies

      - build:
          requires:
            - lint

      - test:
          requires:
            - lint

  publish-to-npm:
    jobs:
      - install-dependencies: *filter-tagged

      - lint:
          <<: *filter-tagged
          requires:
            - install-dependencies

      - build:
          <<: *filter-tagged
          requires:
            - lint

      - test:
          <<: *filter-tagged
          requires:
            - lint

      - release:
          <<: *filter-tagged
          requires:
            - build
            - test

      - publish-release-to-github:
          <<: *filter-tagged
          requires:
            - release
