# Environment variables required in CircleCI:
#
#         $NPM_TOKEN -- NPM publishing auth token.
# $GITHUB_REPO_TOKEN -- GitHub repo-scoped auth token (for use with GREN).

version: 2.1

aliases:
  - &workspace-root
    /home/circleci/project

  - &attach-workspace
    attach_workspace:
      at: *workspace-root

  - &dependency-cache-key
    v1-dependency-cache-{{ checksum "yarn.lock" }}

  - &dependency-paths
    paths:
      - node_modules

  - &dist-paths
    paths:
      - dist

  - &semver-regex # https://rgxdb.com/r/40OZ1HN5
    /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/

  - &filter-any-tag
    filters:
      tags:
        only: /.*/

executors:
  default:
    docker:
      - image: circleci/node:10-browsers
  github:
    docker:
      - image: cibuilds/github:0.10

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - restore_cache:
          key: *dependency-cache-key
      - run:
          name: Install App Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          <<: *dependency-paths
          key: *dependency-cache-key
      - persist_to_workspace:
          <<: *dependency-paths
          root: *workspace-root

  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint TypeScripts
          command: yarn lint

  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Build modules
          command: yarn build
      - persist_to_workspace:
          <<: *dist-paths
          root: *workspace-root

  test:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run tests
          command: yarn test

  release:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish packages to NPM
          command: npm publish

  publish-release-to-github:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Install github-release-notes package
          command: yarn global add github-release-notes
      - run:
          name: Create a release and publish to GitHub
          command: gren --override --token $GITHUB_REPO_TOKEN

workflows:
  version: 2.1
  default:
    jobs:
      - install-dependencies: *filter-any-tag

      - lint:
          requires:
            - install-dependencies
          <<: *filter-any-tag

      - build:
          requires:
            - lint
          <<: *filter-any-tag

      - test:
          requires:
            - lint
          <<: *filter-any-tag

      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
            tags:
              only: *semver-regex

      - publish-release-to-github:
          requires:
            - release
